### ISSUE TITLE
Alternative to building a new repository/code base

### ISSUE THREAD

**Issue by camold** [HarryMWinters/fastapi-oidc#1]
Hi Harry,
thank you very much for the time you invested into the code of this repository!
I have had to walk the very stony path of figuring out how OpenID Connect and a resource server in FastAPI could work together, myself. And this helped quite a lot in understanding some details.

I also came up with a solution and was wondering what you were thinking about it. My approach was to use a maximum of the standard (existing) libraries to avoid any self-introduced security issues.
Also, I have tried to use the security models from FastAPI in order to automatically have them listed in the OpenAPI docs.

Basically, the two tools I am using are authlib (for verification of the access_token, which in my case is a Json Web Token (JWT)) and the FastAPI security model.

Here is how it should look once https://github.com/swagger-api/swagger-ui/issues/3517 is fixed.
The code should already work (more or less - my final version is a bit more complex since I still try to work around the mentioned swagger-ui problem). Just a login via swagger-ui is not possible yet.

```python

from fastapi.security.open_id_connect_url import OpenIdConnect
from starlette.middleware.sessions import SessionMiddleware
from authlib.integrations.starlette_client import OAuth
from fastapi import HTTPException
from fastapi import Request
from fastapi import Depends
from fastapi import status
import string
import random

# create your app first....
# then

# middleware required for authlib - though if you look into the code it is only used to obtain the "nonce"
# which is in this case always None and should not be checked anyways
# (since we are the resource server and the nonce is specified by the identity provider)
# but to reuse the code in authlib, we need to have the middleware installed
app.add_middleware(
    SessionMiddleware,
    secret_key="".join(random.choice(string.ascii_letters) for _ in range(16)),
)

oicd_discovery_url = "...." # the url before .well_known/...

authlib_oauth = OAuth()
authlib_oauth.register(
    name="myapp",
    server_metadata_url=oicd_discovery_url,
    #client_kwargs={"scope": "openid email offline_access profile"},
    #client_id="some-client-id", # if enabled, authlib will also check that the access token belongs to this client id (audience)
)

fastapi_oauth2 = OpenIdConnect(
    openIdConnectUrl=oicd_discovery_url,
    scheme_name="My Authentification Method",
)

async def current_user(
    request: Request, token: Optional[str] = Depends(fastapi_oauth2)
):
    # we could query the identity provider to give us some information about the user
    # userinfo = await self.authlib_oauth.myapp.userinfo(token={"access_token": token})

    # in my case, the JWT already contains all the information so I only need to decode and verify it
    try:
        # note that this also validates the JWT by validating all the claims
        user = await authlib_oauth.myapp.parse_id_token(
            request, token={"id_token": token}
        )
    except Exception as exp:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Supplied authentication could not be validated ({exp})",
        )
    return user

@app.get( "/me" )
def me( user = Depends(current_user)):
     return user

```

It seems to me that authlib also checks a few more claims than you do in your auth.py.
Comments highly appreciated. Maybe it also helps.

Best regards,
Carsten

**Comment by HarryMWinters** [comment]
Hey @camold 

Thanks so much for opening this and letting me know the repo was useful (at least in a demonstrative sense). It's been a minute since I wrote this but I'll take a peak tonight. I'm all for avoiding an unnecessary repo and dependency where possible.

Cheers,
Harry

**Comment by HarryMWinters** [comment]
After review I think you've got a point about your excerpt above being equivalent to the repo as is. There still might be some value to the `types.py` and having a repo for fastapi-oidc code though. I'll add a warning on import that references this issue so people are at least made aware of a straightforward DIY implementation.

**Comment by camold** [comment]
Hey @HarryMWinters,
thanks for the review and also letting me know I didn't get anything wrong.
I'm still buffled by the fact that implementing a ressource server in Python with oidc took me a long time to figure out - really there is no good documentation on such a seemingly simple task out there.
Let's hope we spare some other people some time with this.

**Comment by samedii** [comment]
For anyone else looking into this
```
oicd_discovery_url = "...." # the url before .well_known/...
```
This comment is incorrect. It should include the the "well_known" e.g.
```
oicd_discovery_url = "http://localhost:8080/auth/realms/my-realm/.well-known/openid-configuration"
```

**Comment by HarryMWinters** [comment]
Hello @des1redState,

I'm glad glad you found this thread helpful. Accolades to @samedii and @camold for their work. It **is** surprising how complicated it is to implement OIDC w/ FastAPI. 

I want to caveat my answer with the acknowledgment that it's been a long time since I worked on middleware and that I've not used authlib much at all. That said here are my thoughts.

1. Have you tested this? I have not but I assume it's working as intended when you test with Postman or cURL or other tools.

2. This is my biggest point. It seems that in your `auth` function/endpoint after validating the OIDC token you dump the information into the session cookie. I don't think this is a security flaw per-se since the cookie is signed but it might be worth considering what the benefits to doing so are versus continuing to rely on the token provided by the Identity Provider. [StackOverflow](https://stackoverflow.com/questions/47349434/can-i-securely-store-an-openid-connect-id-token-and-access-token-in-a-cookie-if)

3. I think your middleware approach is sound. Especially for bigger apps where it might be easy to forget to manually add identity checks to an endpoint. If you think it would be useful I'd be happy to add an example using this library but that might be of limited use if you're using AuthLib which actually has token _generating_ functionality. 

Take all the above with a healthy skepticism and hopefully we got more eyes on this. I'm curious what I missed. Good luck and thanks for posting 🤙
